default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: ibctodo_development

test:
  <<: *default
  database: ibctodo_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
